### ISSUE TITLE
[BUG] Every page on "Index management" raises an error popup when opening 

### ISSUE THREAD

**Issue by Mehdi-Bendriss** [canonical/opensearch-dashboards-operator#36]
The Index management / state management policies page raises an error: 
```
[security_exception] no permissions for [cluster:admin/opendistro/ism/policy/search] and User [name=kibanaserver, backend_roles=[], requestedTenant=__user__]
```

![image](https://github.com/canonical/opensearch-dashboards-operator/assets/45567724/4809f2c0-37a5-4cf3-9ef7-2714ee579ade)

Different error are raised when opening other pages under the index management section.

**Comment by juditnovak** [comment]
If I'm correct, this happens when logged in as `kibanaserver`. 

Once logging in as a "normal" user, we shouldn't have this problem... However in case we do, is it OK to re-visit this (and all similar issues) within the scope of https://warthogs.atlassian.net/browse/DPE-4398 , and have this issue closed as a duplicate?
